name: Deploy to Webstore
'on':
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    name: ' Build ${{ matrix.platform }}'
    strategy:
      matrix:
        platform:
          - chrome
          - firefox
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - name: Browser Platform Publish
      - uses: plasmo-corp/bpp@v2
      - with:
          keys: ${{ secrets.SUBMIT_KEYS }}
